# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[(b'VIAF', b'VIAF')], max_length=4)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='concepts.Concept')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_relations', to=settings.AUTH_USER_MODEL)),
                ('external', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_concepts', to='concepts.Concept')),
            ],
        ),
    ]
