# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
