# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_auto_20160506_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=True, help_text=' If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource. '),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='public',
            field=models.BooleanField(default=True, help_text=' If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource. '),
        ),
        migrations.AlterField(
            model_name='contentrelation',
            name='content_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='cookies.Resource'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='public',
            field=models.BooleanField(default=True, help_text=' If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource. '),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=True, help_text=' If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource. '),
        ),
    ]
