# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-10 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_auto_20170326_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionauthorization',
            name='granted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_resource_auths', to=settings.AUTH_USER_MODEL),
        ),
    ]
