# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0005_userjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='GilesSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_file_ids', models.TextField()),
                ('_file_details', models.TextField()),
                ('content_resources', models.ManyToManyField(related_name='content_in_giles_sessions', to='cookies.Resource')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giles_sessions', to=settings.AUTH_USER_MODEL)),
                ('resources', models.ManyToManyField(related_name='giles_sessions', to='cookies.Resource')),
            ],
        ),
    ]
