# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0006_gilessession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gilessession',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Collection'),
        ),
    ]
