# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 14:38
from __future__ import unicode_literals

import cookies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0007_relation_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='file',
            field=models.FileField(blank=True, help_text=' Drop a file onto this field, or click "Choose File" to select a file on your computer. ', max_length=2000, null=True, upload_to=cookies.models._resource_file_name),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text=' Drop a file onto this field, or click "Choose File" to select a file on your computer. ', max_length=2000, null=True, upload_to=cookies.models._resource_file_name),
        ),
    ]
