# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0007_gilessession_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='next_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_page', to='cookies.Resource'),
        ),
    ]
