# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0008_resource_next_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_value', models.TextField()),
            ],
        ),
    ]
