# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 13:18
from __future__ import unicode_literals

import cookies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0008_auto_20170412_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conceptentity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['id'], 'verbose_name': 'metadata relation'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterField(
            model_name='collection',
            name='file',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=cookies.models._resource_file_name),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='gilesupload',
            name='state',
            field=models.CharField(choices=[(b'PD', b'Pending'), (b'EQ', b'Enqueued'), (b'ST', b'Sent'), (b'DO', b'Done'), (b'SE', b'Send error'), (b'GE', b'Giles error'), (b'PE', b'Process error'), (b'CE', b'Callback error'), (b'AS', b'Assigned')], max_length=2),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='relation',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=cookies.models._resource_file_name),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
    ]
