# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0009_auto_20170509_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_source',
            field=models.CharField(blank=True, choices=[(b'GL', b'Giles'), (b'WB', b'Web'), (b'HT', b'HathiTrust')], max_length=2, null=True),
        ),
    ]
