# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-19 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0011_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cookies.Dataset')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='cookies.Resource')),
            ],
        ),
    ]
