# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0012_auto_20160921_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='target_instance_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='contenttypes.ContentType'),
        ),
    ]
