# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0013_auto_20160923_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conceptentity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
