# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0014_auto_20160923_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTimeValue',
        ),
        migrations.DeleteModel(
            name='DateValue',
        ),
        migrations.DeleteModel(
            name='FloatValue',
        ),
        migrations.DeleteModel(
            name='IntegerValue',
        ),
        migrations.DeleteModel(
            name='StringValue',
        ),
    ]
