# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-22 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0014_auto_20170519_1557'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='relation',
            index_together=set([('source_type', 'source_instance_id'), ('target_type', 'target_instance_id')]),
        ),
    ]
