# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0015_auto_20170522_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='sort_order',
            field=models.FloatField(default=0),
        ),
    ]
