# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0015_auto_20160930_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
