# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-16 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0016_auto_20170523_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=2000)),
                ('hidden', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.')),
                ('namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI')),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.ResourceContainer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('end_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_end', to='cookies.Resource')),
                ('entity_type', models.ForeignKey(blank=True, help_text=b'Specifying a type helps to determine what metadata fields are appropriate for this resource, and can help with searching. Note that type-specific filtering of metadata fields will only take place after this resource has been saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Type', verbose_name=b'type')),
                ('start_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_start', to='cookies.Resource')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'entities',
            },
        ),
    ]
