# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0017_auto_20161004_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='on_type',
        ),
        migrations.RemoveField(
            model_name='authorization',
            name='to_do',
        ),
        migrations.RemoveField(
            model_name='event',
            name='by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='did',
        ),
        migrations.RemoveField(
            model_name='event',
            name='on_type',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
