# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0017_contentregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_through',
            field=models.CharField(blank=True, choices=[(b'Web', b'Web UI'), (b'API', b'API')], max_length=3),
        ),
        migrations.AddField(
            model_name='conceptentity',
            name='created_through',
            field=models.CharField(blank=True, choices=[(b'Web', b'Web UI'), (b'API', b'API')], max_length=3),
        ),
        migrations.AddField(
            model_name='contentregion',
            name='created_through',
            field=models.CharField(blank=True, choices=[(b'Web', b'Web UI'), (b'API', b'API')], max_length=3),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='priority',
            field=models.IntegerField(choices=[(10, b'High priority'), (20, b'Medium priority'), (30, b'Low priority')], default=30),
        ),
        migrations.AddField(
            model_name='relation',
            name='created_through',
            field=models.CharField(blank=True, choices=[(b'Web', b'Web UI'), (b'API', b'API')], max_length=3),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_through',
            field=models.CharField(blank=True, choices=[(b'Web', b'Web UI'), (b'API', b'API')], max_length=3),
        ),
    ]
