# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 19:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0018_auto_20161004_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 4, 19, 17, 52, 513725, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentrelation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
