# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0018_auto_20180129_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_through',
            field=models.CharField(choices=[(b'WEB', b'Web UI'), (b'API', b'API')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='created_through',
            field=models.CharField(choices=[(b'WEB', b'Web UI'), (b'API', b'API')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contentregion',
            name='created_through',
            field=models.CharField(choices=[(b'WEB', b'Web UI'), (b'API', b'API')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created_through',
            field=models.CharField(choices=[(b'WEB', b'Web UI'), (b'API', b'API')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_through',
            field=models.CharField(choices=[(b'WEB', b'Web UI'), (b'API', b'API')], max_length=3, null=True),
        ),
    ]
