# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0019_auto_20180207_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetsnapshot',
            name='has_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasetsnapshot',
            name='has_metadata',
            field=models.BooleanField(default=False),
        ),
    ]
