# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0019_auto_20161004_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_source',
            field=models.CharField(blank=True, choices=[(b'GL', b'Giles'), (b'WB', b'Web')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
