# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-03 16:10
from __future__ import unicode_literals

from django.db import migrations
import pg_fts.fields

from pg_fts.migrations import CreateFTSIndexOperation, CreateFTSTriggerOperation
from pg_fts.migrations import UpdateVectorOperation

class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0020_auto_20180323_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name_index',
            field=pg_fts.fields.TSVectorField(default='', dictionary=b'simple', editable=False, fields=(b'name',), null=True, serialize=False),
        ),

        # The following migration ops are NOT auto-generated.

        # Creates 'gin' index in the field 'name_index'.
        CreateFTSIndexOperation(
            name='resource',
            fts_vector='name_index',
            index='gin'
        ),

        # Index the existing documents
        UpdateVectorOperation(
                name='resource',
                fts_vector='name_index',
        ),

        # Create trigger to index every newly added document
        CreateFTSTriggerOperation(
                name='resource',
                fts_vector='name_index',
        ),
    ]
