# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0020_auto_20161005_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 7, 314946)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptentity',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 18, 403195)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentrelation',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 26, 155120)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gilessession',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 35, 291640)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 42, 747657)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 51, 763713)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 34, 58, 19971)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userjob',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 19, 35, 5, 340096)),
            preserve_default=False,
        ),
    ]
