# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0020_auto_20161005_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptentity',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
