# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0021_auto_20161006_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptentity',
            options={'permissions': (('view_entity', 'View entity'), ('change_authorizations', 'Change authorizations'), ('view_authorizations', 'View authorizations'))},
        ),
    ]
