# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0021_auto_20161006_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentrelation',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gilessession',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userjob',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
