# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0021_resource_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='uri',
            field=models.CharField(db_index=True, help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='uri',
            field=models.CharField(db_index=True, help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='contentregion',
            name='uri',
            field=models.CharField(db_index=True, help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='uri',
            field=models.CharField(db_index=True, help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uri',
            field=models.CharField(db_index=True, help_text=b'You may provide your own URI, or allow the system to assign one automatically.', max_length=255, verbose_name=b'URI'),
        ),
    ]
