# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0022_auto_20161014_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'permissions': (('view_relation', 'View relation'), ('change_authorizations', 'Change authorizations'), ('view_authorizations', 'View authorizations')), 'verbose_name': 'metadata relation'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
