# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0022_auto_20161006_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 35, 57, 417938)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 5, 626536)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentrelation',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 13, 690406)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gilessession',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 19, 578500)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gilesupload',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 25, 706498)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 35, 586778)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 40, 32115)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userjob',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 36, 47, 562898)),
            preserve_default=False,
        ),
    ]
