# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0022_auto_20180406_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.TextField(blank=True, db_column=b'location', null=True, verbose_name=b'URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.TextField(blank=True, db_column=b'location', null=True, verbose_name=b'URL'),
        ),
    ]
