# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0023_auto_20161006_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='conceptentity',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='gilessession',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='gilesupload',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='updated',
        ),
    ]
