# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0023_auto_20180426_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gilesupload',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
