# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0023_auto_20180426_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='location',
            new_name='_location',
        ),
        migrations.AddField(
            model_name='resource',
            name='location_id',
            field=models.CharField(blank=True, help_text=b'Instead of storing the complete resource URL in `location`, use this field to store the unique part of URL and generate the complete URL at runtime.', max_length=255, null=True),
        ),
    ]
