# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0023_auto_20161014_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GilesToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=255)),
                ('for_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giles_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text=b'Specifying a type helps to determine what metadata fields are appropriate for this resource, and can help with searching. Note that type-specific filtering of metadata fields will only take place after this resource has been saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Type', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=True, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically (recommended).', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text=b'Specifying a type helps to determine what metadata fields are appropriate for this resource, and can help with searching. Note that type-specific filtering of metadata fields will only take place after this resource has been saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Type', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='public',
            field=models.BooleanField(default=True, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically (recommended).', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text=b'Specifying a type helps to determine what metadata fields are appropriate for this resource, and can help with searching. Note that type-specific filtering of metadata fields will only take place after this resource has been saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Type', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically (recommended).', max_length=255, verbose_name=b'URI'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text=b'Specifying a type helps to determine what metadata fields are appropriate for this resource, and can help with searching. Note that type-specific filtering of metadata fields will only take place after this resource has been saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Type', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=True, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uri',
            field=models.CharField(help_text=b'You may provide your own URI, or allow the system to assign one automatically (recommended).', max_length=255, verbose_name=b'URI'),
        ),
    ]
