# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-05 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0024_auto_20180803_2320'),
        ('cookies', '0024_resource_location_id'),
    ]

    operations = [
    ]
