# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0024_auto_20161006_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 48, 9, 296548)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptentity',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 48, 17, 672618)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 48, 40, 233115)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 6, 18, 48, 46, 905080)),
            preserve_default=False,
        ),
    ]
