# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0025_userjob_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='result_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
