# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0026_auto_20161104_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=False, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='conceptentity',
            name='public',
            field=models.BooleanField(default=False, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='public',
            field=models.BooleanField(default=False, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=False, help_text=b'If a resource is not public it will only be accessible to logged-in users and will not appear in public search results. If this option is selected, you affirm that you have the right to upload and distribute this resource.'),
        ),
    ]
