# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0027_auto_20161107_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gilesupload',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gilesupload',
            name='updated',
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='content_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giles_upload', to='cookies.Resource'),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gilesupload',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
