# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0028_auto_20161107_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='gilesupload',
            name='fail',
            field=models.BooleanField(default=False),
        ),
    ]
