# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0029_gilesupload_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookies.Collection'),
        ),
    ]
