# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0030_collection_part_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entities', models.ManyToManyField(related_name='identities', to='cookies.ConceptEntity')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookies.ConceptEntity')),
            ],
        ),
    ]
