# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0031_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_resources', to='cookies.Collection'),
        ),
    ]
