# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:13
from __future__ import unicode_literals

from django.db import migrations


def populate_resource_belongs_to(apps, schema_editor):
    Resource = apps.get_model("cookies", "Resource")
    Collection = apps.get_model("cookies", "Collection")
    for resource in Resource.objects.all():
        collection = resource.part_of.first()
        if not collection:

            try:
                collection = resource.parent.first().for_resource.part_of.first()
            except AttributeError:
                pass
        resource.belongs_to = collection
        resource.save()


def nope(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0032_resource_belongs_to'),
    ]

    operations = [
        migrations.RunPython(populate_resource_belongs_to, nope)
    ]
