# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0034_auto_20161118_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptentity',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_conceptentities', to='cookies.Collection'),
        ),
        migrations.AddField(
            model_name='relation',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='native_relations', to='cookies.Collection'),
        ),
    ]
