# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 11:56
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from django.contrib.contenttypes.models import ContentType


def populate_belongs_to(apps, schema_editor):
    Resource = apps.get_model("cookies", "Resource")
    Collection = apps.get_model("cookies", "Collection")
    Relation = apps.get_model("cookies", "Relation")
    Field = apps.get_model("cookies", "Field")
    resource_type = ContentType.objects.get_for_model(Resource)

    for collection in Collection.objects.all().values_list('id', flat=True):
        resource_ids = Resource.objects.filter(belongs_to=collection).values_list('id', flat=True)
        relations = Relation.objects.filter(source_type_id=resource_type.id, source_instance_id__in=resource_ids).distinct()
        relations.update(belongs_to_id=collection)
        for relation in relations:
            ttype = ContentType.objects.get(pk=relation.target_type_id)
            if ttype.model in ['value', 'type']:
                continue
            target = ttype.model_class().objects.get(pk=relation.target_instance_id)

            if target.belongs_to:
                continue

            target.belongs_to_id = collection
            target.save()

        relations = Relation.objects.filter(target_type_id=resource_type.id, target_instance_id__in=resource_ids)
        relations.update(belongs_to_id=collection)
        for relation in relations:
            stype = ContentType.objects.get(pk=relation.source_type_id)
            if stype.model in ['value', 'type']:
                continue
            source = stype.model_class().objects.get(pk=relation.source_instance_id)

            if source.belongs_to:
                continue

            source.belongs_to_id = collection
            source.save()


def nope(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0035_auto_20161212_1156'),
    ]

    operations = [
        migrations.RunPython(populate_belongs_to, nope)
    ]
