# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 11:56
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F
from django.contrib.contenttypes.models import ContentType


def populate_belongs_to(apps, schema_editor):
    Resource = apps.get_model("cookies", "Resource")
    Collection = apps.get_model("cookies", "Collection")
    Relation = apps.get_model("cookies", "Relation")
    Field = apps.get_model("cookies", "Field")
    resource_type = ContentType.objects.get_for_model(Resource)

    for collection in Collection.objects.all().values_list('id', flat=True):
        resource_ids = Resource.objects.filter(belongs_to=collection).values_list('id', flat=True)
        relations = Relation.objects.filter(predicate__uri='http://purl.org/dc/terms/isPartOf', source_type=resource_type, source_instance_id__in=resource_ids)
        relations.update(belongs_to=collection)
        for relation in relations:
            if relation.target.belongs_to:
                continue
            relation.target.belongs_to_id = collection
            relation.target.save()

        relations = Relation.objects.filter(predicate__uri='http://purl.org/dc/terms/isPartOf', target_type=resource_type, target_instance_id=resource_ids)
        relations.update(belongs_to=collection)
        for relation in relations:
            if relation.source.belongs_to:
                continue
            relation.source.belongs_to_id = collection
            relation.source.save()






def nope(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0035_auto_20161212_1156'),
    ]

    operations = [
        migrations.RunPython(populate_belongs_to, nope)
    ]
